import {
  pgTable,
  pgEnum,
  uuid,
  text,
  timestamp,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

// ── Enums ─────────────────────────────────────────────────────────────────────
// Values mirror AIProvider and MessageRole from @webapp/types.

export const aiProviderEnum = pgEnum('ai_provider', [
  'openai',
  'anthropic',
  'perplexity',
]);

export const messageRoleEnum = pgEnum('message_role', [
  'user',
  'assistant',
  'system',
]);

// ── Users ─────────────────────────────────────────────────────────────────────

export const users = pgTable('users', {
  id:           uuid('id').primaryKey().defaultRandom(),
  email:        text('email').notNull().unique(),
  displayName:  text('display_name'),
  passwordHash: text('password_hash').notNull(),
  createdAt:    timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt:    timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

// ── Sessions ──────────────────────────────────────────────────────────────────
// id is an opaque random token generated by the application, not a UUID.

export const sessions = pgTable('sessions', {
  id:        text('id').primaryKey(),
  userId:    uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (t) => [
  index('sessions_user_id_idx').on(t.userId),
  index('sessions_expires_at_idx').on(t.expiresAt),
]);

// ── Provider connections ───────────────────────────────────────────────────────
// encrypted_api_key is AES-encrypted at the service layer — never stored plaintext.
// One row per (user, provider). Update in place when user rotates the key.

export const providerConnections = pgTable('provider_connections', {
  id:              uuid('id').primaryKey().defaultRandom(),
  userId:          uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  provider:        aiProviderEnum('provider').notNull(),
  encryptedApiKey: text('encrypted_api_key').notNull(),
  createdAt:       timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt:       timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (t) => [
  uniqueIndex('provider_connections_user_provider_uidx').on(t.userId, t.provider),
]);

// ── Projects ──────────────────────────────────────────────────────────────────

export const projects = pgTable('projects', {
  id:          uuid('id').primaryKey().defaultRandom(),
  userId:      uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  name:        text('name').notNull(),
  description: text('description'),
  createdAt:   timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt:   timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (t) => [
  index('projects_user_id_idx').on(t.userId),
]);

// ── Workspaces ────────────────────────────────────────────────────────────────
// Note: the in-memory Workspace type carries a windowIds[] field. In the DB
// that relationship is captured by chat_windows.workspace_id — no array column needed.

export const workspaces = pgTable('workspaces', {
  id:        uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
  name:      text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (t) => [
  index('workspaces_project_id_idx').on(t.projectId),
]);

// ── Chat windows ──────────────────────────────────────────────────────────────

export const chatWindows = pgTable('chat_windows', {
  id:          uuid('id').primaryKey().defaultRandom(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }),
  title:       text('title').notNull(),
  provider:    aiProviderEnum('provider').notNull(),
  model:       text('model').notNull(),
  createdAt:   timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt:   timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (t) => [
  index('chat_windows_workspace_id_idx').on(t.workspaceId),
]);

// ── Messages ──────────────────────────────────────────────────────────────────
// Messages are append-only — no updated_at.

export const messages = pgTable('messages', {
  id:           uuid('id').primaryKey().defaultRandom(),
  chatWindowId: uuid('chat_window_id').notNull().references(() => chatWindows.id, { onDelete: 'cascade' }),
  role:         messageRoleEnum('role').notNull(),
  content:      text('content').notNull(),
  createdAt:    timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (t) => [
  index('messages_chat_window_id_created_at_idx').on(t.chatWindowId, t.createdAt),
]);
